// <auto-generated />
using System;
using BloodDonationApp.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BloodDonationApp.Infrastructure.Migrations
{
    [DbContext(typeof(BloodDonationContext))]
    [Migration("20240709231739_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AssignedOfficial", b =>
                {
                    b.Property<int>("OfficialID")
                        .HasColumnType("int");

                    b.Property<int>("ActionID")
                        .HasColumnType("int");

                    b.HasKey("OfficialID", "ActionID");

                    b.HasIndex("ActionID");

                    b.ToTable("AssignedOfficial");
                });

            modelBuilder.Entity("BloodDonationApp.Domain.DomainModel.CallToDonate", b =>
                {
                    b.Property<string>("JMBG")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ActionID")
                        .HasColumnType("int");

                    b.Property<bool>("AcceptedTheCall")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowedUp")
                        .HasColumnType("bit");

                    b.HasKey("JMBG", "ActionID");

                    b.HasIndex("ActionID");

                    b.ToTable("CallsToDonate");

                    b.HasData(
                        new
                        {
                            JMBG = "0101995700001",
                            ActionID = 1,
                            AcceptedTheCall = true,
                            ShowedUp = true
                        },
                        new
                        {
                            JMBG = "0101995700001",
                            ActionID = 2,
                            AcceptedTheCall = false,
                            ShowedUp = false
                        },
                        new
                        {
                            JMBG = "0101995700001",
                            ActionID = 3,
                            AcceptedTheCall = true,
                            ShowedUp = false
                        },
                        new
                        {
                            JMBG = "0101995700001",
                            ActionID = 4,
                            AcceptedTheCall = true,
                            ShowedUp = true
                        },
                        new
                        {
                            JMBG = "0101995700001",
                            ActionID = 5,
                            AcceptedTheCall = false,
                            ShowedUp = true
                        });
                });

            modelBuilder.Entity("BloodDonationApp.Domain.DomainModel.CallToVolunteer", b =>
                {
                    b.Property<int>("VolunteerID")
                        .HasColumnType("int");

                    b.Property<int>("ActionID")
                        .HasColumnType("int");

                    b.Property<bool>("AcceptedTheCall")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowedUp")
                        .HasColumnType("bit");

                    b.HasKey("VolunteerID", "ActionID");

                    b.HasIndex("ActionID");

                    b.ToTable("CallsToVolunteer");

                    b.HasData(
                        new
                        {
                            VolunteerID = 1,
                            ActionID = 1,
                            AcceptedTheCall = true,
                            ShowedUp = true
                        },
                        new
                        {
                            VolunteerID = 1,
                            ActionID = 2,
                            AcceptedTheCall = true,
                            ShowedUp = false
                        },
                        new
                        {
                            VolunteerID = 1,
                            ActionID = 3,
                            AcceptedTheCall = false,
                            ShowedUp = true
                        },
                        new
                        {
                            VolunteerID = 1,
                            ActionID = 4,
                            AcceptedTheCall = false,
                            ShowedUp = false
                        },
                        new
                        {
                            VolunteerID = 1,
                            ActionID = 5,
                            AcceptedTheCall = true,
                            ShowedUp = true
                        });
                });

            modelBuilder.Entity("BloodDonationApp.Domain.DomainModel.Donor", b =>
                {
                    b.Property<string>("JMBG")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("BloodType")
                        .HasColumnType("int");

                    b.Property<string>("DonorFullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastDonationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PlaceID")
                        .HasColumnType("int");

                    b.Property<int>("Sex")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("JMBG");

                    b.HasIndex("PlaceID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("Donors");

                    b.HasData(
                        new
                        {
                            JMBG = "0101995700001",
                            BloodType = 6,
                            DonorFullName = "Mladen Mijailovic",
                            IsActive = true,
                            LastDonationDate = new DateTime(2024, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlaceID = 12,
                            Sex = 0,
                            UserID = 1
                        },
                        new
                        {
                            JMBG = "1104345940234",
                            BloodType = 4,
                            DonorFullName = "Vladimir Lazarevic",
                            IsActive = true,
                            LastDonationDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlaceID = 4,
                            Sex = 0,
                            UserID = 2
                        },
                        new
                        {
                            JMBG = "0303995900003",
                            BloodType = 5,
                            DonorFullName = "Sara Djokic",
                            IsActive = true,
                            LastDonationDate = new DateTime(2023, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlaceID = 1,
                            Sex = 1,
                            UserID = 3
                        },
                        new
                        {
                            JMBG = "0407945940004",
                            BloodType = 2,
                            DonorFullName = "Nemanja Markovic",
                            IsActive = false,
                            LastDonationDate = new DateTime(2023, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlaceID = 2,
                            Sex = 0,
                            UserID = 4
                        },
                        new
                        {
                            JMBG = "1604345940234",
                            BloodType = 1,
                            DonorFullName = "Djordje Mirkovic",
                            IsActive = true,
                            LastDonationDate = new DateTime(2023, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlaceID = 2,
                            Sex = 0,
                            UserID = 5
                        },
                        new
                        {
                            JMBG = "1104001765020",
                            BloodType = 1,
                            DonorFullName = "Sandra Kovacevic",
                            IsActive = true,
                            LastDonationDate = new DateTime(2022, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlaceID = 6,
                            Sex = 1,
                            UserID = 6
                        },
                        new
                        {
                            JMBG = "1107001543432",
                            BloodType = 1,
                            DonorFullName = "Petar Nikodijevic",
                            IsActive = true,
                            LastDonationDate = new DateTime(2023, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlaceID = 1,
                            Sex = 0,
                            UserID = 7
                        },
                        new
                        {
                            JMBG = "1505001498898",
                            BloodType = 6,
                            DonorFullName = "Stefan Kotlaja",
                            IsActive = true,
                            LastDonationDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlaceID = 11,
                            Sex = 0,
                            UserID = 8
                        });
                });

            modelBuilder.Entity("BloodDonationApp.Domain.DomainModel.Official", b =>
                {
                    b.Property<int>("OfficialID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OfficialID"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OfficialFullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("OfficialID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("Officials");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Official");

                    b.UseTphMappingStrategy();

                    b.HasData(
                        new
                        {
                            OfficialID = 1,
                            OfficialFullName = "Dunja Nesic",
                            UserID = 13
                        },
                        new
                        {
                            OfficialID = 2,
                            OfficialFullName = "Stefan Jovanovic",
                            UserID = 14
                        },
                        new
                        {
                            OfficialID = 3,
                            OfficialFullName = "Pavle Gasic",
                            UserID = 12
                        });
                });

            modelBuilder.Entity("BloodDonationApp.Domain.DomainModel.Place", b =>
                {
                    b.Property<int>("PlaceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlaceID"));

                    b.Property<string>("PlaceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlaceID");

                    b.ToTable("Places");

                    b.HasData(
                        new
                        {
                            PlaceID = 1,
                            PlaceName = "Smederevo"
                        },
                        new
                        {
                            PlaceID = 2,
                            PlaceName = "Beograd"
                        },
                        new
                        {
                            PlaceID = 3,
                            PlaceName = "Sremska Mitrovica"
                        },
                        new
                        {
                            PlaceID = 4,
                            PlaceName = "Cacak"
                        },
                        new
                        {
                            PlaceID = 5,
                            PlaceName = "Novi Sad"
                        },
                        new
                        {
                            PlaceID = 6,
                            PlaceName = "Nis"
                        },
                        new
                        {
                            PlaceID = 7,
                            PlaceName = "Kraljevo"
                        },
                        new
                        {
                            PlaceID = 8,
                            PlaceName = "Subotica"
                        },
                        new
                        {
                            PlaceID = 9,
                            PlaceName = "Zrenjanin"
                        },
                        new
                        {
                            PlaceID = 10,
                            PlaceName = "Pancevo"
                        },
                        new
                        {
                            PlaceID = 11,
                            PlaceName = "Vlasotince"
                        },
                        new
                        {
                            PlaceID = 12,
                            PlaceName = "Novi Pazar"
                        },
                        new
                        {
                            PlaceID = 13,
                            PlaceName = "Kragujevac"
                        });
                });

            modelBuilder.Entity("BloodDonationApp.Domain.DomainModel.Question", b =>
                {
                    b.Property<int>("QuestionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionID"));

                    b.Property<int>("Flag")
                        .HasColumnType("int");

                    b.Property<string>("QuestionText")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("QuestionID");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            QuestionID = 1,
                            Flag = 0,
                            QuestionText = "Da li redovno (svakodnevno) uzimate bilo kakve lekove?"
                        },
                        new
                        {
                            QuestionID = 2,
                            Flag = 0,
                            QuestionText = "Da li ste poslednja 2-3 dana uzimali bilo kakve lekove (npr. Brufen, Kafetin, Analgin...)?"
                        },
                        new
                        {
                            QuestionID = 3,
                            Flag = 0,
                            QuestionText = "Da li stalno uzimate Aspirin (Cardiopirin)? Da li ste ga uzimali u poslednjih 5 dana?"
                        },
                        new
                        {
                            QuestionID = 4,
                            Flag = 0,
                            QuestionText = "Da li ste do sada ispitivani ili lečeni u bolnici ili ste trenutno na ispitivanju ili bolovanju?"
                        },
                        new
                        {
                            QuestionID = 5,
                            Flag = 0,
                            QuestionText = "Da li ste vadili zub u proteklih 7 dana?"
                        },
                        new
                        {
                            QuestionID = 6,
                            Flag = 0,
                            QuestionText = "Da li ste u poslednjih 7 do 10 dana imali temperaturu preko 38 C, kijavicu, prehladu ili uzimali antibiotike?"
                        },
                        new
                        {
                            QuestionID = 7,
                            Flag = 0,
                            QuestionText = "Da li ste u poslednjih 6 meseci naglo izgubili na težini?"
                        },
                        new
                        {
                            QuestionID = 8,
                            Flag = 0,
                            QuestionText = "Da li ste imali ubode krpelja u proteklih 12 meseci i da li ste se zbog toga javljali lekaru?"
                        },
                        new
                        {
                            QuestionID = 9,
                            Flag = 0,
                            QuestionText = "Da li ste ikada lečeni od epilepsije (padavice), šećerne bolesti, astme, tuberkuloze, infarkta, moždanog udara, malignih oboljenja, mentalnih bolesti ili malarije?"
                        },
                        new
                        {
                            QuestionID = 10,
                            Flag = 0,
                            QuestionText = "Da li bolujete od neke druge hronične bolesti: srca, pluća, bubrega, jetre, želuca i creva, kostiju i zglobova, nervnog sistema, krvi i krvnih sudova?"
                        },
                        new
                        {
                            QuestionID = 11,
                            Flag = 0,
                            QuestionText = "Da li ste u proteklih 6 meseci putovali ili živeli u inostranstvu?"
                        },
                        new
                        {
                            QuestionID = 12,
                            Flag = 0,
                            QuestionText = "Da li ste ikada imali problema sa štitastom žlezdom, hipofizom i/ili primali hormone?"
                        },
                        new
                        {
                            QuestionID = 13,
                            Flag = 0,
                            QuestionText = "Da li imate neke promene na koži ili bolujete od alergije?"
                        },
                        new
                        {
                            QuestionID = 14,
                            Flag = 0,
                            QuestionText = "Da li dugo krvavite posle povrede ili spontano dobijate modrice?"
                        },
                        new
                        {
                            QuestionID = 15,
                            Flag = 0,
                            QuestionText = "Da li ste bolovali ili bolujete od hepatitisa (žutice) A, B ili C?"
                        },
                        new
                        {
                            QuestionID = 16,
                            Flag = 0,
                            QuestionText = "Da li ste u proteklih 6 meseci imali akupunkturu, piercing ili tetovažu?"
                        },
                        new
                        {
                            QuestionID = 17,
                            Flag = 0,
                            QuestionText = "Da li mislite da je postojala mogućnost da se zarazite HIV-om?"
                        },
                        new
                        {
                            QuestionID = 18,
                            Flag = 0,
                            QuestionText = "Da li ste ikada koristili bilo koju vrstu droge?"
                        },
                        new
                        {
                            QuestionID = 19,
                            Flag = 0,
                            QuestionText = "Da li ste ikada koristili preparate koji se zvanično ne izdaju na recept i/ili preparate za bodi bilding (steroide)?"
                        },
                        new
                        {
                            QuestionID = 20,
                            Flag = 0,
                            QuestionText = "Da li znate na koje sve načine ste mogli izložiti sebe riziku od zaraznih, krvlju prenosivih bolesti?"
                        },
                        new
                        {
                            QuestionID = 21,
                            Flag = 0,
                            QuestionText = "Da li ste u proteklih 6 meseci imali neku operaciju ili primili krv?"
                        },
                        new
                        {
                            QuestionID = 22,
                            Flag = 1,
                            QuestionText = "Da li je davalac u dobrom opštem zdravstvenom stanju?"
                        },
                        new
                        {
                            QuestionID = 23,
                            Flag = 1,
                            QuestionText = "Da li davalac ima normalne vitalne znakove (krvni pritisak, puls, temperatura)?"
                        },
                        new
                        {
                            QuestionID = 24,
                            Flag = 1,
                            QuestionText = "Da li su nalazi krvne slike davaoca u granicama normale?"
                        },
                        new
                        {
                            QuestionID = 25,
                            Flag = 1,
                            QuestionText = "Da li je koža davaoca bez osipa, rana ili infekcija?"
                        },
                        new
                        {
                            QuestionID = 26,
                            Flag = 1,
                            QuestionText = "Da li je srčani ritam davaoca regularan bez znakova aritmije?"
                        },
                        new
                        {
                            QuestionID = 27,
                            Flag = 1,
                            QuestionText = "Da li su pluća davaoca čista i bez znakova infekcije ili zagušenja?"
                        },
                        new
                        {
                            QuestionID = 28,
                            Flag = 1,
                            QuestionText = "Da li davalac ima normalan nivo hemoglobina?"
                        },
                        new
                        {
                            QuestionID = 29,
                            Flag = 1,
                            QuestionText = "Da li davalac pokazuje znake anemije ili drugih krvnih poremećaja?"
                        },
                        new
                        {
                            QuestionID = 30,
                            Flag = 1,
                            QuestionText = "Da li je rezultat testa za HIV, hepatitis B, hepatitis C i sifilis negativan?"
                        },
                        new
                        {
                            QuestionID = 31,
                            Flag = 1,
                            QuestionText = "Da li davalac ima adekvatan nivo hidratacije i nije dehidriran?"
                        });
                });

            modelBuilder.Entity("BloodDonationApp.Domain.DomainModel.Questionnaire", b =>
                {
                    b.Property<string>("JMBG")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ActionID")
                        .HasColumnType("int");

                    b.Property<bool>("Approved")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DateOfMaking")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("QRCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuestionnaireTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("JMBG", "ActionID");

                    b.HasIndex("ActionID");

                    b.ToTable("Questionnaires");

                    b.HasData(
                        new
                        {
                            JMBG = "0101995700001",
                            ActionID = 5,
                            Approved = false,
                            DateOfMaking = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            QuestionnaireTitle = "Upitnik za akciju Daj krv, spasi zivot u Novom Pazaru",
                            Remark = "Odbijen zbog niskog krvnog pritiska",
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            JMBG = "1104345940234",
                            ActionID = 1,
                            Approved = true,
                            DateOfMaking = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            QuestionnaireTitle = "Upitnik za akciju na FON-u",
                            Remark = "/",
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            JMBG = "1104345940234",
                            ActionID = 3,
                            Approved = true,
                            DateOfMaking = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            QuestionnaireTitle = "Upitnik za akciju u Vozdovim kapijama",
                            Remark = "Sve ok",
                            RowVersion = new byte[0]
                        });
                });

            modelBuilder.Entity("BloodDonationApp.Domain.DomainModel.QuestionnaireQuestion", b =>
                {
                    b.Property<int>("QuestionID")
                        .HasColumnType("int");

                    b.Property<string>("QuestionnaireJMBG")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("QuestionnaireActionID")
                        .HasColumnType("int");

                    b.Property<bool>("Answer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("QuestionID", "QuestionnaireJMBG", "QuestionnaireActionID");

                    b.HasIndex("QuestionnaireJMBG", "QuestionnaireActionID");

                    b.ToTable("QuestionnaireQuestions");
                });

            modelBuilder.Entity("BloodDonationApp.Domain.DomainModel.RedCross", b =>
                {
                    b.Property<int>("RedCrossID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RedCrossID"));

                    b.Property<string>("InstitutionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlaceID")
                        .HasColumnType("int");

                    b.HasKey("RedCrossID");

                    b.HasIndex("PlaceID");

                    b.ToTable("RedCross");

                    b.HasData(
                        new
                        {
                            RedCrossID = 1,
                            InstitutionName = "CKSmederevo",
                            PlaceID = 1
                        },
                        new
                        {
                            RedCrossID = 2,
                            InstitutionName = "CK_Vozdovac",
                            PlaceID = 1
                        },
                        new
                        {
                            RedCrossID = 3,
                            InstitutionName = "Crveni krst NBG",
                            PlaceID = 3
                        },
                        new
                        {
                            RedCrossID = 4,
                            InstitutionName = "CK Sremska Mitrovica",
                            PlaceID = 4
                        });
                });

            modelBuilder.Entity("BloodDonationApp.Domain.DomainModel.Role", b =>
                {
                    b.Property<string>("RoleID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleID");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleID = "donor-role",
                            RoleName = "Donor"
                        },
                        new
                        {
                            RoleID = "volunteer-role",
                            RoleName = "Volunteer"
                        },
                        new
                        {
                            RoleID = "red-cross",
                            RoleName = "RedCrossOfficial"
                        },
                        new
                        {
                            RoleID = "itk",
                            RoleName = "MedicalOfficial"
                        },
                        new
                        {
                            RoleID = "official",
                            RoleName = "Official"
                        },
                        new
                        {
                            RoleID = "in-charge",
                            RoleName = "OfficialInCharge"
                        });
                });

            modelBuilder.Entity("BloodDonationApp.Domain.DomainModel.TransfusionAction", b =>
                {
                    b.Property<int>("ActionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActionID"));

                    b.Property<DateTime>("ActionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ActionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActionTimeFromTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExactLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OfficialID")
                        .HasColumnType("int");

                    b.Property<int>("PlaceID")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("ActionID");

                    b.HasIndex("OfficialID");

                    b.HasIndex("PlaceID");

                    b.ToTable("TransfusionActions");

                    b.HasData(
                        new
                        {
                            ActionID = 1,
                            ActionDate = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ActionName = "FON humanitarna akcija",
                            ActionTimeFromTo = "10:00 - 16:00",
                            ExactLocation = "Fakultet organizacionih nauka",
                            OfficialID = 1,
                            PlaceID = 2,
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            ActionID = 2,
                            ActionDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ActionName = "Sportski centar Smederevo",
                            ActionTimeFromTo = "08:00 - 18:00",
                            ExactLocation = "Sportski centar",
                            OfficialID = 1,
                            PlaceID = 1,
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            ActionID = 3,
                            ActionDate = new DateTime(2024, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ActionName = "Dobrovoljno davanje krvi u Vozdovim kapijama",
                            ActionTimeFromTo = "09:00 - 14:00",
                            ExactLocation = "Crveni Krst Vozdovac",
                            OfficialID = 1,
                            PlaceID = 2,
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            ActionID = 4,
                            ActionDate = new DateTime(2024, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ActionName = "Krv za zivot",
                            ActionTimeFromTo = "11:00 - 17:00",
                            ExactLocation = "Opšta bolnica Niš",
                            OfficialID = 1,
                            PlaceID = 6,
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            ActionID = 5,
                            ActionDate = new DateTime(2024, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ActionName = "Daj krv, spasi zivot",
                            ActionTimeFromTo = "10:00 - 15:00",
                            ExactLocation = "Dom Zdravlja NP",
                            OfficialID = 1,
                            PlaceID = 12,
                            RowVersion = new byte[0]
                        });
                });

            modelBuilder.Entity("BloodDonationApp.Domain.DomainModel.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            Email = "mladen.mijailovic@gmail.com",
                            Password = "$2a$11$YXWfiQbwUkNIfWBngbEF0.ObkG0YIOPHhf51bL/SxfdTrtSHMWnOG"
                        },
                        new
                        {
                            UserID = 2,
                            Email = "vladimir.lazarevic@gmail.com",
                            Password = "$2a$11$w5pkJ2avFOnRzr974jmxcOOEcM9um6iw/hrd.iCKu4AP2DHLxskca"
                        },
                        new
                        {
                            UserID = 3,
                            Email = "sara.djokic@gmail.com",
                            Password = "$2a$11$m.u2OWBZzVJOSxfZv0.7u.rTgfjTiyBsSf9f9G/eUUjwg3UgfkOlq"
                        },
                        new
                        {
                            UserID = 4,
                            Email = "nemanja.markovic@gmail.com",
                            Password = "$2a$11$C7nZQrsriG7U2LlRM5tjde/LCT9aQiOsfYhG0hH8P.RfN2EVLjCfy"
                        },
                        new
                        {
                            UserID = 5,
                            Email = "djordje.mirkovic@gmail.com",
                            Password = "$2a$11$DF68.5gFIz/5UIvfR4aUpeKRUPvDMhssFB2km9bU0JKglNmlc9CE6"
                        },
                        new
                        {
                            UserID = 6,
                            Email = "sandra.kovacevic@gmail.com",
                            Password = "$2a$11$CA8LY5pbFyTdHfygczRrY.JHef7m9pqo8QC4Qx7bk9lE2gKT3ZJFe"
                        },
                        new
                        {
                            UserID = 7,
                            Email = "petar.nikodijevic@gmail.com",
                            Password = "$2a$11$q4k.42a.othLaSFpGqDE5eBA4avZTopH2ci5ZkuXTZEsFMuERO41S"
                        },
                        new
                        {
                            UserID = 8,
                            Email = "stefan.kotlaja@gmail.com",
                            Password = "$2a$11$H/iRvurucqB7r34iT/dkhuEKcDcRPATTfe3tlGwllN4nCUIMabahy"
                        },
                        new
                        {
                            UserID = 9,
                            Email = "iva.djokovic@gmail.com",
                            Password = "$2a$11$89OJHSDKAUPMhPnviN5rqee46r5eVsNTEJxxzOWpXSNuactNsX2UG"
                        },
                        new
                        {
                            UserID = 10,
                            Email = "nevena.dukic@gmail.com",
                            Password = "$2a$11$2fkgpOBFFxj4CUZIDEk7HOJDpKRk7kOcH/EcFft0ReNn31VSPoA82"
                        },
                        new
                        {
                            UserID = 11,
                            Email = "predrag.tanaskovic@gmail.com",
                            Password = "$2a$11$rklEmEk.kcpWhp1Pkrdry.qiusspLOmOJBLRryvDeAQUi/rQFzyK6"
                        },
                        new
                        {
                            UserID = 12,
                            Email = "pavle.gasic@gmail.com",
                            Password = "$2a$11$HOWDneaw0n0uog7mFhWt.uuN1O75sQzuDi8NTFR9HQ3/WhP16m1f6"
                        },
                        new
                        {
                            UserID = 13,
                            Email = "dunja.nesic@gmail.com",
                            Password = "$2a$11$R.EhCbON4CQyTodCXI7LNeLWY4jWTPbJxPUNbAA/sPFrnJGgHMNpK"
                        },
                        new
                        {
                            UserID = 14,
                            Email = "stefan.jovanovic@gmail.com",
                            Password = "$2a$11$Ha2WR4l7FQWOsiWEJ3y0NePcDz4kikR3B95XmfBabZ/qVncUdekRG"
                        },
                        new
                        {
                            UserID = 15,
                            Email = "veljko.nedeljkovic@gmail.com",
                            Password = "$2a$11$5CMei/a5zyJXKO3E0fa4Oe9g3V8tT4wXdfI/kofch7GblkQF7wCZm"
                        },
                        new
                        {
                            UserID = 16,
                            Email = "minja.filip@gmail.com",
                            Password = "$2a$11$xUh2f86BxYjfdMH8U.HOeeBNwK33SrJBQXlDOHEyUKWPV/b7KwN6i"
                        },
                        new
                        {
                            UserID = 17,
                            Email = "sofija.filip@gmail.com",
                            Password = "$2a$11$RRxZ8KjFaNioLokTKPVOu.ACwd0Z0N9acS.KC/zWuw1yTrAHNEAtO"
                        },
                        new
                        {
                            UserID = 18,
                            Email = "vasilije.nesic@gmail.com",
                            Password = "$2a$11$P078LI76mfrd38LMAq/xOeNWSiMd1xZ6V7J3nYnvZ3dJrbupKWPky"
                        },
                        new
                        {
                            UserID = 19,
                            Email = "vojin.cvetkovic@gmail.com",
                            Password = "$2a$11$qop8Sqon7QCvUdkgmlilrOk4MUPj69bHYf83PyeXtkyBrpBpFuf2C"
                        },
                        new
                        {
                            UserID = 20,
                            Email = "veljko.cvetkovic@gmail.com",
                            Password = "$2a$11$JxJgmzBqh3arvxSMAIMiPOC4aDn5vHLcnXOZJTIsQ4RfqaHKdMqJ2"
                        },
                        new
                        {
                            UserID = 21,
                            Email = "nikola.miletic@gmail.com",
                            Password = "$2a$11$oGUtg.IHoZU3aLGWm2/C5O.aTailywnkmzzVzScPoDTfyRGEpbY0q"
                        });
                });

            modelBuilder.Entity("BloodDonationApp.Domain.DomainModel.Volunteer", b =>
                {
                    b.Property<int>("VolunteerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VolunteerID"));

                    b.Property<DateTime>("DateFreeFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateFreeTo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int>("RedCrossID")
                        .HasColumnType("int");

                    b.Property<int>("Sex")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<string>("VolunteerFullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VolunteerID");

                    b.HasIndex("RedCrossID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("Volunteers");

                    b.HasData(
                        new
                        {
                            VolunteerID = 1,
                            DateFreeFrom = new DateTime(2024, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateFreeTo = new DateTime(2024, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2001, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RedCrossID = 2,
                            Sex = 1,
                            UserID = 9,
                            VolunteerFullName = "Iva Djokovic"
                        },
                        new
                        {
                            VolunteerID = 2,
                            DateFreeFrom = new DateTime(2024, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateFreeTo = new DateTime(2024, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2001, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RedCrossID = 2,
                            Sex = 1,
                            UserID = 10,
                            VolunteerFullName = "Nevena Dukic"
                        },
                        new
                        {
                            VolunteerID = 3,
                            DateFreeFrom = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateFreeTo = new DateTime(2024, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2001, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RedCrossID = 1,
                            Sex = 0,
                            UserID = 14,
                            VolunteerFullName = "Predrag Tanaskovic"
                        },
                        new
                        {
                            VolunteerID = 4,
                            DateFreeFrom = new DateTime(2024, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateFreeTo = new DateTime(2024, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2001, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RedCrossID = 1,
                            Sex = 0,
                            UserID = 15,
                            VolunteerFullName = "Veljko Nedeljkovic"
                        },
                        new
                        {
                            VolunteerID = 6,
                            DateFreeFrom = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateFreeTo = new DateTime(2024, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2001, 9, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RedCrossID = 1,
                            Sex = 1,
                            UserID = 16,
                            VolunteerFullName = "Minja Filip"
                        },
                        new
                        {
                            VolunteerID = 7,
                            DateFreeFrom = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateFreeTo = new DateTime(2024, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2001, 9, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RedCrossID = 1,
                            Sex = 1,
                            UserID = 17,
                            VolunteerFullName = "Sofija Filip"
                        },
                        new
                        {
                            VolunteerID = 8,
                            DateFreeFrom = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateFreeTo = new DateTime(2024, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2002, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RedCrossID = 2,
                            Sex = 0,
                            UserID = 18,
                            VolunteerFullName = "Vasilije Nesic"
                        },
                        new
                        {
                            VolunteerID = 9,
                            DateFreeFrom = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateFreeTo = new DateTime(2024, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2000, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RedCrossID = 2,
                            Sex = 0,
                            UserID = 19,
                            VolunteerFullName = "Vojin Cvetkovic"
                        },
                        new
                        {
                            VolunteerID = 10,
                            DateFreeFrom = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateFreeTo = new DateTime(2024, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(2000, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RedCrossID = 2,
                            Sex = 0,
                            UserID = 20,
                            VolunteerFullName = "Veljko Cvetkovic"
                        },
                        new
                        {
                            VolunteerID = 11,
                            DateFreeFrom = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateFreeTo = new DateTime(2024, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1999, 9, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RedCrossID = 2,
                            Sex = 0,
                            UserID = 21,
                            VolunteerFullName = "Nikola Miletic"
                        });
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.Property<string>("RolesRoleID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("UsersUserID")
                        .HasColumnType("int");

                    b.HasKey("RolesRoleID", "UsersUserID");

                    b.HasIndex("UsersUserID");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("BloodDonationApp.Domain.DomainModel.MedicalWorker", b =>
                {
                    b.HasBaseType("BloodDonationApp.Domain.DomainModel.Official");

                    b.Property<string>("HealthcareOccupation")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("MedicalWorker");
                });

            modelBuilder.Entity("BloodDonationApp.Domain.DomainModel.RedCrossWorker", b =>
                {
                    b.HasBaseType("BloodDonationApp.Domain.DomainModel.Official");

                    b.Property<int>("RedCrossID")
                        .HasColumnType("int");

                    b.HasIndex("RedCrossID");

                    b.HasDiscriminator().HasValue("RedCrossWorker");
                });

            modelBuilder.Entity("AssignedOfficial", b =>
                {
                    b.HasOne("BloodDonationApp.Domain.DomainModel.TransfusionAction", null)
                        .WithMany()
                        .HasForeignKey("ActionID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BloodDonationApp.Domain.DomainModel.Official", null)
                        .WithMany()
                        .HasForeignKey("OfficialID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("BloodDonationApp.Domain.DomainModel.CallToDonate", b =>
                {
                    b.HasOne("BloodDonationApp.Domain.DomainModel.TransfusionAction", "Action")
                        .WithMany("ListOfCallsToDonors")
                        .HasForeignKey("ActionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BloodDonationApp.Domain.DomainModel.Donor", "Donor")
                        .WithMany("CallsToDonate")
                        .HasForeignKey("JMBG")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Action");

                    b.Navigation("Donor");
                });

            modelBuilder.Entity("BloodDonationApp.Domain.DomainModel.CallToVolunteer", b =>
                {
                    b.HasOne("BloodDonationApp.Domain.DomainModel.TransfusionAction", "Action")
                        .WithMany("ListOfCallsToVolunteers")
                        .HasForeignKey("ActionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BloodDonationApp.Domain.DomainModel.Volunteer", "Volunteer")
                        .WithMany("CallsToVolunteer")
                        .HasForeignKey("VolunteerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Action");

                    b.Navigation("Volunteer");
                });

            modelBuilder.Entity("BloodDonationApp.Domain.DomainModel.Donor", b =>
                {
                    b.HasOne("BloodDonationApp.Domain.DomainModel.Place", "Place")
                        .WithMany()
                        .HasForeignKey("PlaceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BloodDonationApp.Domain.DomainModel.User", "User")
                        .WithOne()
                        .HasForeignKey("BloodDonationApp.Domain.DomainModel.Donor", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Place");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BloodDonationApp.Domain.DomainModel.Official", b =>
                {
                    b.HasOne("BloodDonationApp.Domain.DomainModel.User", "User")
                        .WithOne()
                        .HasForeignKey("BloodDonationApp.Domain.DomainModel.Official", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BloodDonationApp.Domain.DomainModel.Questionnaire", b =>
                {
                    b.HasOne("BloodDonationApp.Domain.DomainModel.TransfusionAction", "Action")
                        .WithMany("ListOfQuestionnaires")
                        .HasForeignKey("ActionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BloodDonationApp.Domain.DomainModel.Donor", "Donor")
                        .WithMany("ListOfQuestionnaires")
                        .HasForeignKey("JMBG")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Action");

                    b.Navigation("Donor");
                });

            modelBuilder.Entity("BloodDonationApp.Domain.DomainModel.QuestionnaireQuestion", b =>
                {
                    b.HasOne("BloodDonationApp.Domain.DomainModel.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BloodDonationApp.Domain.DomainModel.Questionnaire", "Questionnaire")
                        .WithMany("ListOfQuestions")
                        .HasForeignKey("QuestionnaireJMBG", "QuestionnaireActionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("Questionnaire");
                });

            modelBuilder.Entity("BloodDonationApp.Domain.DomainModel.RedCross", b =>
                {
                    b.HasOne("BloodDonationApp.Domain.DomainModel.Place", "Place")
                        .WithMany()
                        .HasForeignKey("PlaceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Place");
                });

            modelBuilder.Entity("BloodDonationApp.Domain.DomainModel.TransfusionAction", b =>
                {
                    b.HasOne("BloodDonationApp.Domain.DomainModel.Official", "ActionCoordinator")
                        .WithMany("CreatedActions")
                        .HasForeignKey("OfficialID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BloodDonationApp.Domain.DomainModel.Place", "Place")
                        .WithMany()
                        .HasForeignKey("PlaceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActionCoordinator");

                    b.Navigation("Place");
                });

            modelBuilder.Entity("BloodDonationApp.Domain.DomainModel.Volunteer", b =>
                {
                    b.HasOne("BloodDonationApp.Domain.DomainModel.RedCross", "RedCross")
                        .WithMany()
                        .HasForeignKey("RedCrossID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BloodDonationApp.Domain.DomainModel.User", "User")
                        .WithOne()
                        .HasForeignKey("BloodDonationApp.Domain.DomainModel.Volunteer", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RedCross");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.HasOne("BloodDonationApp.Domain.DomainModel.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesRoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BloodDonationApp.Domain.DomainModel.User", null)
                        .WithMany()
                        .HasForeignKey("UsersUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BloodDonationApp.Domain.DomainModel.RedCrossWorker", b =>
                {
                    b.HasOne("BloodDonationApp.Domain.DomainModel.RedCross", "RedCross")
                        .WithMany()
                        .HasForeignKey("RedCrossID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RedCross");
                });

            modelBuilder.Entity("BloodDonationApp.Domain.DomainModel.Donor", b =>
                {
                    b.Navigation("CallsToDonate");

                    b.Navigation("ListOfQuestionnaires");
                });

            modelBuilder.Entity("BloodDonationApp.Domain.DomainModel.Official", b =>
                {
                    b.Navigation("CreatedActions");
                });

            modelBuilder.Entity("BloodDonationApp.Domain.DomainModel.Questionnaire", b =>
                {
                    b.Navigation("ListOfQuestions");
                });

            modelBuilder.Entity("BloodDonationApp.Domain.DomainModel.TransfusionAction", b =>
                {
                    b.Navigation("ListOfCallsToDonors");

                    b.Navigation("ListOfCallsToVolunteers");

                    b.Navigation("ListOfQuestionnaires");
                });

            modelBuilder.Entity("BloodDonationApp.Domain.DomainModel.Volunteer", b =>
                {
                    b.Navigation("CallsToVolunteer");
                });
#pragma warning restore 612, 618
        }
    }
}
